# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: move to publish dir
        run: mkdir publish && mv *html publish/
      - name: HTMLMinifier
        # You may pin to the exact commit or the version.
        # uses: emepetres/html-minifier-action@3212e848160959942d14de2e02b4e72632586714
        uses: emepetres/html-minifier-action@v1
        with:
        # Path to root directory containing HTML files
          rootDir: "publish"
          # Prints minification details
          verbose: true
          # Additional flags to pass to HTMLMinifier, separted by comma. See https://github.com/kangax/html-minifier#options-quick-reference. Use ! to indicate false value of a flag.
          flags: "caseSensitive, collapseBooleanAttributes, collapseInlineTagWhitespace, collapseWhitespace, decodeEntities, html5, minifyCSS, minifyJS, minifyURLs, processConditionalComments, processScripts, removeAttributeQuotes, removeComments, removeOptionalTags, removeEmptyAttributes, removeEmptyElements, removeRedundantAttributes, removeRedundantAttributes, removeScriptTypeAttributes, removeStyleLinkTypeAttributes, removeTagWhitespace, sortAttributes, sortClassName useShortDoctype"
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
        
        
